### ISSUE TITLE
Update for Twig 3

### ISSUE THREAD

**Issue by darkalchemy** [odan/twig-translation#4]
Now that twig-extensions is deprecated and not available for Twig 3, how can this be updated to work with Twig 3? I can't even find 'trans' or i18n extension as part of the 'Core Extensions'. 

Or, is this something that will have to be created from scratch, without using Twig's Core Extensions?

I'm not asking you to rewrite this, only asking your opinion.  I am considering using your class for compiling the templates along with [PHP-I18N](https://github.com/delight-im/PHP-I18N) in a project of mine.

Thanks for all you do. I am learning alot, at least I hope I am, from reading and using your projects and tutorials.

**Comment by odan** [comment]
Hi @darkalchemy The plan is to remove the dependencies from `twig/translations` and replace it with `twig/twig`. I realized that I don't need the `twig/translations` because this extension just adds a simple `__` function to the Twig environment and doesn't need a i18n token parser. So upgrading should be quite easy. I will release a new version `2.0` as soon as possible.

**Comment by odan** [comment]
Version 2.0 has been released. I would be happy to hear if it works for you too.

**Comment by darkalchemy** [comment]
Wow, that was fast. It will be tomorrow after work before I can try it out. 

Thank you
